{% set name = "langchainplus-sdk" %}
{% set version = "0.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/langchainplus_sdk-{{ version }}.tar.gz
  sha256: c911a98fd2d02baa48f742b7d700fd6a55f11c9a545ee5d66b08825940c9a32e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - poetry-core
    - pip
  run:
    - python >=3.8.1,<4.0
    - pydantic >=1.0.0,<2.0.0
    - requests >=2.0.0,<3.0.0
    - tenacity >=8.1.0,<9.0.0

test:
  imports:
    - langchainplus_sdk
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Client library to connect to the LangChainPlus LLM Tracing and Evaluation Platform.
  license: MIT
  license_file: PLEASE_ADD_LICENSE_FILE

extra:
  recipe-maintainers:
    - YYYasin19
